import type { Metadata } from "next";
import "../styles/core.scss";
import { Roboto } from "next/font/google";
import BaseLayout from "@/layout/BaseLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
    weight: ["400", "500", "700"],
    subsets: ["latin"],
    style: ["normal", "italic"],
    display: "swap",
    preload: true,
    variable: "--font-family"
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <head>
        <title>Biochallenge - UIDAI | IIIT, Hyderabad</title>
        <meta
            name="description"
            content="Biochallenge - Unique Identification Authority of India | International Institute of Information Technology, Hyderabad"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <meta
            name="author"
            content="Mahen Gandhi <mahengandhi19@gmail.com>, Kaustubh Kishore <kaustubh@kkishore.in>"
        />
        <link rel="icon" href="/favicon.ico"/>
      </head>
      <body>
      <main className={roboto.className}>
        <BaseLayout>  {children}</BaseLayout>
      </main>
      <div id={"portal"}/>
      </body>
      </html>
  );
}
